# Generated by Django 4.0.6 on 2022-07-17 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('out', 'out'), ('in', 'in')], max_length=3)),
                ('part', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('transaction_amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
